#!/bin/sh

IMAGEVER=$($apache_VERSION | sed s/\.//)

cat <<EOF
This is a S2I apache $apache_VERSION CentOS base image:
To use it, install S2I: https://github.com/openshift/source-to-image
Sample invocation:
$ s2i build https://github.com/sheena13/apache-s2i.git \\
    --context-dir=/${apache_VERSION}/test/test-app/ sheena/apache-${IMAGEVER}-centos7 sheena-test-app
You can then run the resulting image via:
$ docker run -p 8080:80 -p 8443:443 sheena-test-app
EOF
