#!/bin/sh

IMAGEVER=$($CADDY_VERSION | sed s/\.//)

cat <<EOF
This is a S2I Caddy $CADDY_VERSION CentOS base image:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:

$ s2i build https://github.com/Sheena13/apache-s2i.git \\
    --context-dir=/${CADDY_VERSION}/test/test-app/ openshift/caddy-${IMAGEVER}-centos7 caddy-test-app

You can then run the resulting image via:

$ docker run -p 8080:80 -p 8443:443 caddy-test-app
EOF
